name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Production
    defaults:
      run:
        working-directory: /var/www/ukuvota.world
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build
  
    - name: Archive build artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-artifact
        path: dist

    - name: Send webhook
      env:
        REPO_NAME: ${{ github.event.repository.name }}
        WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
        REF: "refs/heads/main"
      run: |
        payload="{\"repository\": {\"name\": \"$REPO_NAME\"}, \"ref\": \"$REF\"}"
        signature=$(printf "%s" "$payload" | openssl dgst -sha1 -hmac "${WEBHOOK_SECRET}" | sed 's/^.*= //')

        curl -X POST https://webhooks.alphion.xyz/hooks/ansible-playbook \
          -H 'Content-Type: application/json' \
          -H "X-Hub-Signature: sha1=${signature}" \
          -d "$payload"
        
