name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Production

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Cache dependencies
      uses: actions/cache@v2.1.6
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Archive build artifact
      id: get-url
      uses: actions/upload-artifact@v2
      with:
        name: build-artifact
        path: dist

    - name: Debug secret
      run: |
        echo "The value of MY_SECRET is ${{ secrets.MY_SECRET }}"

    - name: Send webhook
      env:
        ARTIFACT_URL: ${{ steps.get-url.outputs.artifact-url }}
        REPO_NAME: ${{ basename github.repository }}
        WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}

      run: |
        echo "ARTIFACT_URL=$ARTIFACT_URL"
        echo "REPO_NAME=$REPO_NAME"
        echo "WBEHOOK_SECRET=$WEBHOOK_SECRET"
        payload='{"artifact_url": "'"$ARTIFACT_URL"'", "repository": {"name": "'"$REPO_NAME"'"} }'
        curl -X POST https://webhooks.alphion.xyz/hooks/ansible-playbook \
          -H 'Content-Type: application/json' \
          -H "X-Hub-Secret: ${WEBHOOK_SECRET}" \
          -d "$payload"
        
